name: Unzip
on: workflow_dispatch
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -q 3105-main.zip
          cp -a 3105-main/. .
          rm -rf 3105-main 3105-main.zip
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Unzip source"
          git push
